ci:
    autofix_prs: false
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
     # Run the linter.
     - id: ruff
       types_or: [ python, pyi, jupyter ]
       args: [ --fix ]
     # Run the formatter.
     - id: ruff-format
       types_or: [ python, pyi, jupyter ]

-   repo: https://github.com/PyCQA/docformatter    # To format the doc strings to conform PEP257
    rev: v1.7.5
    hooks:
    - id: docformatter
      args: [--in-place]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

-   repo: https://github.com/pre-commit/pre-commit-hooks    # Some common pre-commit hooks
    rev: v4.6.0
    hooks:
    - id: check-yaml               # Checks the syntax of .yaml files.
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer        # Makes sure files end with a newline.
    - id: trailing-whitespace      # Checks for any tabs or spaces after the last non-whitespace character on the line.
    - id: check-docstring-first    # Checks that code comes after the docstrings.
