[format]
# preserve mixture of single and double quotes
quote-style = "preserve"

[per-file-ignores]
# E402 Module level import not at top of cell
"applications/data_analysis/sample.ipynb" = ["E402"]
"applications/file_io/sample.ipynb" = ["E402"]
"applications/plot_types/contour.ipynb" = ["E402"]
"conf.py" = ["E402"]
