[format]
# preserve mixture of single and double quotes
quote-style = "preserve"

[lint]
# Format the doc strings to conform PEP257
select = ["D401"]
# Skip E402 Module level import not at top of cell
ignore = ["E402"]
