name: 💡 Feature request
description: Suggest an idea for this project
title: "[💡]: "
labels: ["support", "triage"]

body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this feature request!"

  - type: textarea
    id: summary
    attributes:
      label: "Describe the addition you would like to see."
      description: "the more information the better!"
    validations:
      required: true

  - type: dropdown
    id: ncl
    attributes:
      label: "Is this a request for something that previously existed in NCL?"
      options:
        - "Yes"
        - "No"
        - "Unknown"
    validations:
        required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here"
    validations:
      required: false