name: 💡 Feature Request
description: Suggest an idea for this project or submit a new page
title: "[💡]: "
labels: ["support", "triage"]

body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this feature request!"

  - type: textarea
    id: summary
    attributes:
      label: "Describe the addition you would like to see."
      description: "the more information the better!"
    validations:
      required: true

  - type: dropdown
    id: ncl
    attributes:
      label: "Is this a request for something that previously existed in NCL?"
      options:
        - "Yes"
        - "No"
        - "Unknown"
    validations:
        required: true

  - type: dropdown
    id: template
    attributes:
      label: "Choose an application template"
      description: "For more information about the [different page templates](https://ncar.github.io/geocat-applications/CONTRIBUTING.html#types-of-geocat-applications-pages)"
      options:
        - "Python"
        - "NCL"
        - "Receipts"
    validations:
        required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here"
    validations:
      required: false
