; addfile
; Adapted from https://www.ncl.ucar.edu/Document/Functions/Built-in/addfile.shtml

; NetCDF
; .nc
; .cdf
; .netcdf

; GRIB v1 and v2
; .gr
; .gr1
; .grb
; .grib
; .grb1
; .grib1
; .gr2
; grb2
; grib2

; HDF
; .hdf
; .hd

; HDF-EOS
; .hdfeos
; .he2
; .he4

; HDF5
; .h5

; HDF-EOS5
; .he5

; CCM
; .ccm

; Shapefile
; .shp (shapefile)
; .mif (MapInfo)
; .gmt (Generic Mapping Tools)
; .rt1 (TIGER)
