name: deploy

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact (zipped book) created by previous build step'
        required: false
        default: book-zip
        type: string
      is_preview:
        description: 'Is this a preview deployment?'
        required: false
        default: false
        type: string
      destination_dir:
        description: 'Path to publish to on GitHub Pages, relative to site root. We use this to deploy previews in a subdirectory.'
        required: false
        default: ''
        type: string
      publish_dir:
        description: 'Publish dir for the peaceiris/actions-gh-pages action'
        required: false
        default: '_build/html'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Download merged artifact
        if: inputs.is_preview != 'true'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      # For the preview, the official download-artifact action doesn't work
      # because the artifact is created by a different workflow
      - name: Download preview artifact
        if: inputs.is_preview == 'true'
        uses: dawidd6/action-download-artifact@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-book.yaml
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ inputs.artifact_name }}

      - name: Unzip the book
        run: |
          rm -rf _build/html
          unzip book.zip
          rm -f book.zip

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.publish_dir }}
          enable_jekyll: false
          keep_files: true  # This preserves existing previews from open PRs
          destination_dir: ${{ inputs.destination_dir }}
