name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”

jobs:
  build:
    uses: './.github/workflows/build.yml'

  deploy:
    needs: build
    uses: './.github/workflows/gh-pages.yml'
